base_frame_id: panda_link0
task_frame_id: task
ee_grasp_offset_z: -0.038
scan_joints: 
  - [0.010, -1.479, 0.100, -2.416, 0.089, 1.402, 0.851]
  - [-0.520, -0.796, 0.912, -1.672, 0.091, 1.281, 0.871]
  - [0.032, 0.459, 0.074, -0.839, 0.015, 0.777, 0.833]
  - [0.092, -0.626, -0.551, -1.837, 0.165, 1.238, 0.900]

table_height: 0.14  # Measured from the base frame specified above

grasp_selection: "auto"  # Choice: manual, auto

arm_velocity_scaling_drop: 0.3
arm_velocity_scaling_grasp: 0.2

vgn:
    model: $(find vgn)/assets/models/vgn_conv.pth
