cartesian_velocity_controller:
    type: mopa_controllers/CartesianVelocityController
    arm_id: panda
    rate_limiting:
        linear:
            velocity: 0.5
            acceleration: 8.0
            jerk: 1000.0
        angular:
            velocity: 0.5
            acceleration: 5.0
            jerk: 2000.0
