joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

effort_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  constraints:
    goal_time: 0.5
  gains:
    panda_joint1: { p: 50, i: 0, d: 20 }
    panda_joint2: { p: 10000, i: 0, d: 500 }
    panda_joint3: { p: 100, i: 0, d: 10 }
    panda_joint4: { p: 1000, i: 0, d: 50 }
    panda_joint5: { p: 100, i: 0, d: 10 }
    panda_joint6: { p: 100, i: 0, d: 10 }
    panda_joint7: { p: 10, i: 0.5, d: 0.1 }

#franka_gripper:
#  type: position_controllers/GripperActionController
#  joint: panda_finger_joint1

#gazebo_ros_control:
#  pid_gains:
#    panda_finger_joint1: {p: 100, i: 0.1, d: 10, i_clamp: 0.2}
#    panda_finger_joint2: {p: 100, i: 0.1, d: 10, i_clamp: 0.2}
#    front_left_wheel: {p: 1, i: 0.1, d: 0, i_clamp: 0.2}
#    front_right_wheel: {p: 1, i: 0.1, d: 0, i_clamp: 0.2}
#    rear_left_wheel: {p: 1, i: 0.1, d: 0, i_clamp: 0.2}
#    rear_right_wheel: {p: 1, i: 0.1, d: 0, i_clamp: 0.2}
