joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

position_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  constraints:
    goal_time: 0.5

franka_gripper:
  type: position_controllers/GripperActionController
  joint: panda_finger_joint1

gazebo_ros_control:
  pid_gains:
    panda_finger_joint1: {p: 100, i: 0, d: 50}
    panda_finger_joint2: {p: 100, i: 0, d: 50}
