# # MoveIt-specific simulation settings
# moveit_sim_hw_interface:
#   joint_model_group: controllers_initial_group_
#   joint_model_group_pose: controllers_initial_pose_
# # Settings for ros_control control loop
# generic_hw_control_loop:
#   loop_hz: 300
#   cycle_time_error_threshold: 0.01
# # Settings for ros_control hardware interface
# hardware_interface:
#   joints:
#     - virtual_joint
#     - front_rocker
#     - front_left_wheel
#     - front_right_wheel
#     - rear_left_wheel
#     - rear_right_wheel
#     - panda_joint1
#     - panda_joint2
#     - panda_joint3
#     - panda_joint4
#     - panda_joint5
#     - panda_joint6
#     - panda_joint7
#     - panda_finger_joint1
#   sim_control_mode: 1  # 0: position, 1: velocity
# # Publish all joint states
# # Creates the /joint_states topic necessary in ROS
# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 50
# controller_list:
#   - name: panda_hand_controller
#     action_ns: follow_joint_trajectory
#     default: True
#     type: FollowJointTrajectory
#     joints:
#       - panda_finger_joint1
#   - name: franka_gripper
#     action_ns: follow_joint_trajectory
#     default: True
#     type: FollowJointTrajectory
#     joints:
#       - panda_joint1
#       - panda_joint2
#       - panda_joint3
#       - panda_joint4
#       - panda_joint5
#       - panda_joint6
#       - panda_joint7
#       - panda_finger_joint1

 controller_list:
  - name: franka/position_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: franka/gripper_action_controller
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
