name: moma CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  CATKIN_WS_PATH: moma_ws

jobs:
  build-dev:
    name: Build dev docker image
    runs-on: ubuntu-latest
    outputs:
      docker_image_name: ${{ steps.meta.outputs.tags }}
    steps:
    - name: Check out moma repo
      uses: actions/checkout@v3
      with:
        path: moma_ws/src/moma
        submodules: recursive
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        flavor: prefix=dev
    - name: Build and push docker
      uses: docker/build-push-action@v4
      with:
        context: ./moma_ws/src/moma/docker/
        file: ./moma_ws/src/moma/docker/dev.Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-robot:
    name: Build robot docker image
    runs-on: ubuntu-latest
    outputs:
      docker_image_name: ${{ steps.meta.outputs.tags }}
    steps:
    - name: Check out moma repo
      uses: actions/checkout@v3
      with:
        path: moma_ws/src/moma
        submodules: recursive
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        flavor: prefix=robot
    - name: Build and push docker
      uses: docker/build-push-action@v4
      with:
        context: ./moma_ws/src/moma/docker/
        file: ./moma_ws/src/moma/docker/robot.Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Checks out the demo branch and builds a docker image of that.
  build-demo:
    name: Build robot docker image
    runs-on: ubuntu-latest
    outputs:
      docker_image_name: ${{ steps.meta.outputs.tags }}
    steps:
    - name: Check out moma repo
      uses: actions/checkout@v3
      with:
        ref: demo
        path: moma_ws/src/moma
        submodules: recursive
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        flavor: prefix=demo
    - name: Build and push docker
      uses: docker/build-push-action@v4
      with:
        context: ./moma_ws/src/moma/docker/
        file: ./moma_ws/src/moma/docker/demo.Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
