name: moma Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the dev Docker image
      run: docker build . --file ./docker/scripts/dev.Dockerfile --tag moma_dev:$(date +%s)
      
